# Site settings
title: Lukas Froehlich
description: Lukas Froehlichs Resume
favicon: /assets/img/avatar.png
baseurl:
url: lukasfroehlich.com
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  name: Lukas Froehlich
  title: Knowledge Enthusiast
  introduction: My name is Lukas Froehlich and am intereasted in a wide variaty of subjects.
  address: San Francisco, CA
  email: lukasfroehlich1@gmail.com
  link: http://lukasfroehlich.com
  github: lukasfroehlich1
  linkedin: lukasfroehlich
  gavatar: /assets/img/portrait.jpg
  workHistory:
    - work1:
      company: Hulu
      location: Santa Monica, CA
      title: Software Developer Intern
      started: 2015
      duration: (June 2015 - August 2015)
      description: Worked on the payments team to develop a generalized anomaly detection service. The service easily allowed the user to add queries to be monitored. Worked with Echo State Networks along with a few other algorithms. Worked with the payments code base to filter out all sensitive information from the logs.
      tools: Python, Javascript, Scala, Mongo, D3
    - work2:
      company: Study Session Leader
      location: Cal Poly - San Luis Obispo
      started: 2014
      duration: (Sep. 2014 - Dec. 2014)
      description: Intruct and guide students weekly by paralleling the Phyiscs curriculum. Includes preparing worksheets and problems that actively challenge students.
  projects:
    - project1: 
      title: IR Sensor
      subtitle: Automated Device Interaction
      started: 2015
      description: Worked on a web service to send IR commands to a raspberry pi which then were transmitted to a living room device. A backend handled the tasks and task history while the raspberry pi hosted its own endpoint that converted commands to IR signals. Both endpoints were written in python using flask.
    - project2: 
      title: Poker Bot
      subtitle: Highly Optimized Gambling
      started: 2015
      description: Created a poker game that would allow for users to connect poker bots and play poker. Componnts included managing various gamestates, win conditions and game flow. The backend was written in python using flask.
      url: https://github.com/GordonGustafson/Poker
  educationHistory:
    - education1:
      organization: California Polytechnic University - San Luis Obispo
      degree: Bachelor of Science
      major: Computer Engineering
      started: 2013
      duration: (2013 - present)
      description: 
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: German
      proficiency: Fluent
    - language3:
      name: Chinese
      proficiency: Fluent
  experiencedProgramming:
    - skill1:
      name: Python
    - skill2:
      name: Java
  learningProgramming:
    - skill1:
      name: Bootstrap
    - skill2:
      name: JavaScript
    - skill3:
      name: D3
    - skill4:
      name: Scala
    - skill4:
      name: Haskell
